[build]
  publish = "."
  command = "python build.py"

[build.environment]
  PYTHON_VERSION = "3.11"
  NETLIFY = "1"
  DJANGO_SETTINGS_MODULE = "dareproject.settings"

[functions]
  directory = "netlify/functions"

# Health check endpoint
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/django-app"
  status = 200

# Admin panel
[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/django-app"
  status = 200

# API endpoints
[[redirects]]
  from = "/dare/*"
  to = "/.netlify/functions/django-app"
  status = 200

# Authentication endpoints
[[redirects]]
  from = "/login/*"
  to = "/.netlify/functions/django-app"
  status = 200

[[redirects]]
  from = "/signup/*"
  to = "/.netlify/functions/django-app"
  status = 200

[[redirects]]
  from = "/logout/*"
  to = "/.netlify/functions/django-app"
  status = 200

# Static files
[[redirects]]
  from = "/static/*"
  to = "/staticfiles/:splat"
  status = 200

# Catch-all for Django app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/django-app"
  status = 200