services:
  - type: web
    name: django-dare-exchange
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn dareproject.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: django-dare-db
          property: connectionString

databases:
  - name: django-dare-db
    databaseName: django_dare_exchange
    user: django_user