# Generated by Django 5.2.5 on 2025-08-11 16:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dare',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('verified', 'Verified')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='DareCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_text', models.TextField(help_text='Describe how you completed the dare')),
                ('proof_image', models.ImageField(blank=True, help_text='Upload an image as proof (optional)', null=True, upload_to='dare_proofs/')),
                ('proof_video_url', models.URLField(blank=True, help_text='Link to video proof (YouTube, etc.)', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by_poster', models.BooleanField(default=False)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='dare.dare')),
            ],
        ),
        migrations.CreateModel(
            name='DareRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rate from 1 (boring) to 5 (amazing)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment about the dare')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='dare.dare')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dare', 'rated_by')},
            },
        ),
    ]
