# Generated by Django 5.2.5 on 2025-08-16 08:08

from django.db import migrations
from django.contrib.auth.hashers import make_password


def populate_initial_data(apps, schema_editor):
    Category = apps.get_model('dare', 'Category')
    Dare = apps.get_model('dare', 'Dare')
    User = apps.get_model('auth', 'User')
    
    # Create categories
    categories_data = [
        {'name': 'Physical Challenge', 'description': 'Physical activities and sports challenges'},
        {'name': 'Creative', 'description': 'Art, music, and creative challenges'},
        {'name': 'Social', 'description': 'Social interaction and community challenges'},
        {'name': 'Learning', 'description': 'Educational and skill-building challenges'},
        {'name': 'Adventure', 'description': 'Outdoor and adventure challenges'},
        {'name': 'Food', 'description': 'Cooking and food-related challenges'},
        {'name': 'Technology', 'description': 'Tech and coding challenges'},
    ]
    
    created_categories = []
    for cat_data in categories_data:
        category, created = Category.objects.get_or_create(
            name=cat_data['name'],
            defaults={'description': cat_data['description']}
        )
        created_categories.append(category)
    
    # Create demo users
    demo_users_data = [
        {'username': 'admin', 'email': 'admin@dareexchange.com', 'is_staff': True, 'is_superuser': True},
        {'username': 'arjun', 'email': 'arjun@example.com'},
        {'username': 'priya', 'email': 'priya@example.com'},
        {'username': 'rohit', 'email': 'rohit@example.com'},
        {'username': 'sneha', 'email': 'sneha@example.com'},
    ]
    
    created_users = []
    for user_data in demo_users_data:
        user, created = User.objects.get_or_create(
            username=user_data['username'],
            defaults={
                'email': user_data['email'],
                'is_staff': user_data.get('is_staff', False),
                'is_superuser': user_data.get('is_superuser', False),
                'password': make_password('demopass123')
            }
        )
        created_users.append(user)
    
    # Create sample dares
    sample_dares = [
        {
             'title': 'Master 108 Surya Namaskars',
             'description': 'Complete 108 Surya Namaskars (Sun Salutations) in one session. A traditional yoga challenge that tests endurance and devotion!',
             'category': created_categories[0],  # Physical Challenge
             'posted_by': created_users[1],  # arjun
         },
        {
             'title': 'Learn a Classical Indian Raga',
             'description': 'Learn to sing or play a classical Indian raga you\'ve never performed before. Share a recording of your performance.',
             'category': created_categories[1],  # Creative
             'posted_by': created_users[2],  # priya
         },
         {
             'title': 'Feed 50 Street Animals',
             'description': 'Prepare food and feed 50 street dogs or cats in your area. Document this act of compassion and share the experience.',
             'category': created_categories[2],  # Social
             'posted_by': created_users[3],  # rohit
         },
         {
             'title': 'Cook Authentic Biryani from Scratch',
             'description': 'Master the art of making authentic Hyderabadi or Lucknowi biryani from scratch. Share the cooking process and final result!',
             'category': created_categories[5],  # Food
             'posted_by': created_users[1],  # arjun
         },
         {
             'title': 'Complete a 10K Morning Run',
             'description': 'Wake up at 5 AM and complete a 10K run before sunrise. Capture the beautiful morning views and your achievement!',
             'category': created_categories[0],  # Physical Challenge
             'posted_by': created_users[2],  # priya
         },
         {
             'title': 'Create Rangoli Art',
             'description': 'Design and create a beautiful rangoli pattern using traditional or modern techniques. Share your colorful creation!',
             'category': created_categories[1],  # Creative
             'posted_by': created_users[4],  # sneha
         },
         {
             'title': 'Learn Sanskrit Shlokas',
             'description': 'Memorize and recite 5 Sanskrit shlokas with proper pronunciation. Share a video of your recitation.',
             'category': created_categories[3],  # Learning
             'posted_by': created_users[3],  # rohit
         },
         {
             'title': 'Build an Indian Language App',
             'description': 'Create a simple mobile or web app that teaches basic words in any Indian regional language.',
             'category': created_categories[6],  # Technology
             'posted_by': created_users[1],  # arjun
         },
         {
             'title': 'Visit 5 Historical Monuments',
             'description': 'Explore 5 historical monuments in your city or nearby areas. Document their history and significance.',
             'category': created_categories[4],  # Adventure
             'posted_by': created_users[2],  # priya
         },
         {
             'title': 'Master 50 Bhangra Moves',
             'description': 'Learn and perform 50 different Bhangra dance moves. Create an energetic dance video showcasing your skills!',
             'category': created_categories[0],  # Physical Challenge
             'posted_by': created_users[4],  # sneha
         },
    ]
    
    for dare_data in sample_dares:
         Dare.objects.get_or_create(
             title=dare_data['title'],
             defaults={
                 'description': dare_data['description'],
                 'category': dare_data['category'],
                 'posted_by': dare_data['posted_by'],
             }
         )


def reverse_populate_initial_data(apps, schema_editor):
    # This function is called when the migration is reversed
    Category = apps.get_model('dare', 'Category')
    Dare = apps.get_model('dare', 'Dare')
    User = apps.get_model('auth', 'User')
    
    # Delete sample data (optional - you can leave this empty)
    Dare.objects.filter(title__in=[
        'Master 108 Surya Namaskars',
        'Learn a Classical Indian Raga',
        'Feed 50 Street Animals',
        'Cook Authentic Biryani from Scratch',
        'Complete a 10K Morning Run',
        'Create Rangoli Art',
        'Learn Sanskrit Shlokas',
        'Build an Indian Language App',
        'Visit 5 Historical Monuments',
        'Master 50 Bhangra Moves',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dare', '0002_dare_status_darecompletion_darerating'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, reverse_populate_initial_data),
    ]
